# Generated by Django 4.2.4 on 2023-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_features_car_featuers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(max_length=100),
        ),
    ]
